### ISSUE TITLE
Guia de suscripciones

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#10]
Chicos, en la pag web, readme y wiki están los espacios para ingresar la guía...

Cómo la realizamos????????
:question: 
Eve

**Comment by VictoriaYanez** [comment]
Primero debemos implementar MAILCHIMP. Saber como se usa y cómo podríamos utilizar en nuestro proyecto. Conociendo su funcionamiento se establecen los puntos a seguir para los suscriptores.

**Comment by VictoriaYanez** [comment]
Podríamos usar la información de esta página como guía: http://kb.mailchimp.com/es/accounts/account-setup/if-you-dont-have-a-website

El punto a resaltar es lo siguiente: "Cuando creas una nueva cuenta MailChimp, se te pide que facilites un sitio web . Utilizamos tu sitio web para generar la URL para los formularios de suscripción y páginas de agradecimiento de tu lista."

**Comment by VictoriaYanez** [comment]
Tengo entendido que se debe definir la siguiente información: 
![mailchimp](https://cloud.githubusercontent.com/assets/14907412/11321838/5686811a-909c-11e5-914a-f2628158fc5f.png)

Debemos estar de acuerdo para que uno de los integrantes cree la cuenta y se encargue de administrar la lista de suscriptores.

**Comment by MarlonVP** [comment]
La guía de suscriptores ya se ha creado tanto en el Wiki y en el Readme.
