### ISSUE TITLE
nuevos prototipos

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#12]
Hola a todos :D, volví hacer los prototipos, por favor miren, si hay alguna cosa que no estén de acuerdo dupliquen y modifiquen 
:point_up_2: 
https://docs.google.com/drawings/d/1FvQBs02IWZzKexmjcmWyhALeBvRcENxLBT2XMp-KR8k/edit

**Comment by EvelynRegalado** [comment]
Chicos, volvimos a rehacer los prototipos, porfa revisen.... 
No olviden que los comentarios de los issues tambien es calificación!!

:ear:

**Comment by Chucho1991** [comment]
chevere, entonces como rapartimos la elaboración de los prototipos, por ahora solo necesitamos que el sistema navegue sin necesidad de la base de datos

**Comment by sebas1208** [comment]
Muchachos ya hice algunas interfaces con bootstrap y angular. No hay nada funcional todavía. Cualquier cosa me avisan.

[Eva](https://boiling-mesa-6829.herokuapp.com/eva)

**Comment by MarlonVP** [comment]
Gracias Sebas, están muy bien. (Y)
