### ISSUE TITLE
String de Conexión 

### ISSUE THREAD

**Issue by sebas1208** [AppLibresEva/App_Libres_Eva#14]
Les dejos los parámetros para conectarse a la base de datos postgres en heroku.

Host		ec2-54-197-241-24.compute-1.amazonaws.com
Database d4oidal1dhnik8
User	 	 estrtjtxunlbks
Port		 5432
Password	 2vX1e2XuPdQrqtiWs7lrXE3bA8

**Comment by EvelynRegalado** [comment]
Amigo les compartiste a los chicos de los otros grupos?

**Comment by Chucho1991** [comment]
se le agradece

**Comment by sebas1208** [comment]
Les puse en la carpeta publica del dropbox. Pero hay que comunicarles.
