### ISSUE TITLE
Herramienta Votación

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#15]
Hola a todos, encontré una manera para realizar las votaciones, por fa respondan a la encuesta para ver si les parece bien o si cambiamos a otra.... Esta encuesta además servirá como el ejemplo que nos pidió el Inge, asi que la deben realizar lo más pronto posible..
Gracias.. 
:v:

**Comment by EvelynRegalado** [comment]
https://applibleseva.doodle.com/poll/sfcavicinuwqpz4p esta es la dirección por donde podrán votar xD

**Comment by VictoriaYanez** [comment]
@EvelynRegalado  podrías ubicar el enlace o el medio para acceder a la encuesta

**Comment by VictoriaYanez** [comment]
Ya la probé, creo que es dinámica y la interfaz es fácil de entender. Creo que deberíamos usarla.

**Comment by Chucho1991** [comment]
Me parece bien la herramienta, para votar me dejo sin identificarme, se puede configurar eso?

**Comment by EvelynRegalado** [comment]
:v:

**Comment by MarlonVP** [comment]
Es excelente.

**Comment by MarlonVP** [comment]
Super sencilla y concisa.
