### ISSUE TITLE
Errores commits

### ISSUE THREAD

**Issue by Chucho1991** [AppLibresEva/App_Libres_Eva#16]
Muchachos tenemos que ponernos de acuerdo al momento de programar y hacer los commits estar seguros de sincronizar para evitar conflictos!!!

**Comment by EvelynRegalado** [comment]
El problema fue solucionado, respecto a los commits de usuarios..
:D

**Comment by EvelynRegalado** [comment]
@MarlonVP si tienes algún problema en la codificación, reportarlo.
