### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#17]
Para la elección de la licencia, por favor votar http://doodle.com/poll/4heqwvcnxpx4d9dz

**Comment by Chucho1991** [comment]
hecho!!! la MIT me parece la mas apropiada...

**Comment by EvelynRegalado** [comment]
ya amigos, entonces la licencia queda con la MIT, en la página principal del proyecto ya la pueden encontrar..
:+1:
