### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#4]
![logo eva](https://cloud.githubusercontent.com/assets/14907414/10444355/1a96edec-712b-11e5-8c8d-d6457718c5e0.png)

Encontre este logo para el proyecto.. :dancer:

**Comment by Chucho1991** [comment]
Y si mantenemos el logo que lleva solo las letras?

**Comment by VictoriaYanez** [comment]
El problema es que ese logo ya pertenece a la marca de un automóvil.

**Comment by VictoriaYanez** [comment]
![687474703a2f2f636172747970652e636f6d2f706963732f373936382f736d616c6c2f76616c6d65745f6576615f6c6f676f5f31302e6a7067](https://cloud.githubusercontent.com/assets/14907412/10483827/16dcbd92-721d-11e5-9da0-fe6022f9ac3d.jpg)

**Comment by Chucho1991** [comment]
ya subí a la pagina el logo del carro!!!

**Comment by adrianeguez** [comment]
#3  aqui ya fue respondida su duda
