### ISSUE TITLE
Lista de Subscriptores

### ISSUE THREAD

**Issue by sebas1208** [AppLibresEva/App_Libres_Eva#7]
Dejen aqui ideas o links para la lista de Subscriptores

**Comment by VictoriaYanez** [comment]
Encontré estos tres programas, revisen si alguno nos puede servir
* http://www.sendblaster.es/
* http://es.email-unlimited.com/email-marketing-software.html
 *http://mailchimp.com/

**Comment by EvelynRegalado** [comment]
este video esta bueno para utilizar mailChinp
https://www.youtube.com/watch?v=_ej9tQCK_n8
:octocat:
