### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#8]
Hola chicos,

Edité agunas interfaces en la carpeta compartida de google drive... 

:v:

**Comment by VictoriaYanez** [comment]
Chicos partiendo del trabajo de @EvelynRegalado le cambié los fondos y el orden de algunas de las interfaces. Para que revisen si está bien.

**Comment by Chucho1991** [comment]
yo realice unos cambios mínimos a las interfaces no se que les parece como quedó, en general cambié tipos de letra y colores de las mismas para darle un aspecto mas formal, el logo en la interfaz de inicio

**Comment by EvelynRegalado** [comment]
Chicos en la carpeta hay 3 tipos de prototipos..
¿Qué interfaces utilizamos?

**Comment by Chucho1991** [comment]
En mi opinión las últimas que están

**Comment by VictoriaYanez** [comment]
Si esas vamos a usar, ya están como versión final en el Wiki.
