### ISSUE TITLE
Parámetros del proyecto

### ISSUE THREAD

**Issue by EvelynRegalado** [AppLibresEva/App_Libres_Eva#9]
Chicos.. Estos son los parámetros que debemos entregar en el proyecto.

- Página Web tenga el Logo. 
- Wiki Tenga el Logo. 
- Los colaboradores deben de estar tanto en el Wiki como en la página Web y el Readme. 
- El año y meses en los que ha estado activo el proyecto también deben de ser descritos. 
- Deben de escribir el estado del proyecto (en desarrollo por ejemplo). 
- Guía de como suscribirse al proyecto. 
- Qué tipo de suscripciones hay y cuáles serían sus roles. 
- Describir cada uno de los labels, como utilizarlos para los colaboradores. 
- Cambiar los objetivos a los actuales (ya no es mediante archivos JSON sino se puede conectar con cualquier base de datos – mysql, postgresql, Oracle, mssql, mongodb, etc). 
- Mediante los Issues es cómo  se debe de comunicar el grupo, debe de haber evidencia del trabajo y la coordinación que han tenido mediante esto. 
- En los Issues escribir las características que se han ido desarrollando durante este bimestre y asignarles a un Milestone llamado “1er Biemstre”. 
- Label que estén en español y sean usados algunos de ellos. 
- Usar los “pull request” para hacer los cambios en la Página Web. 
- Dentro de la página web que este implementado la lista de suscriptores con la posibilidad de seleccionar al menos 3 tipos de suscripciones, la de los desarrolladores, la de los colaboradores en general y la de gente interesada. 
- No debe de haber ningún issue “Abierto”. 
- Tanto en la página Web, como en el Wiki deben de tener el prototipo de la interfaz con la navegación. 
:dancers:

**Comment by VictoriaYanez** [comment]
Para tratar todos los puntos una opcion seria establecer la dificultad para dividir que tarea hacer.

**Comment by VictoriaYanez** [comment]
Para tratar todos los puntos una opcion seria establecer la dificultad para dividir que tarea hacer.

**Comment by EvelynRegalado** [comment]
Chicos segun yo, faltan estos items...
- Qué tipo de suscripciones hay y cuáles serían sus roles.
- Mediante los Issues es cómo se debe de comunicar el grupo, debe de haber evidencia del trabajo y la coordinación que han tenido mediante esto.
- Describir cada uno de los labels, como utilizarlos para los colaboradores.
Usar los “pull request” para hacer los cambios en la Página Web.
- Dentro de la página web que este implementado la lista de suscriptores con la posibilidad de seleccionar al menos 3 tipos de suscripciones, la de los desarrolladores, la de los colaboradores en general y la de gente interesada.
- Tanto en la página Web, como en el Wiki deben de tener el prototipo de la interfaz con la navegación.

**Comment by VictoriaYanez** [comment]
Las tareas que han sido realizadas corresponden a las siguiente:

* Página Web tenga el Logo.
* Wiki Tenga el Logo.
* Los colaboradores deben de estar tanto en el Wiki como en la página Web y el Readme.
* En los Issues se han asignardo a un Milestone llamado “1er Biemstre”.
* El año y meses en los que ha estado activo el proyecto también deben de ser descritos.
*Deben de escribir el estado del proyecto (en desarrollo por ejemplo).
* Label que estén en español.
* Cambiar los objetivos a los actuales (ya no es mediante archivos JSON sino se puede conectar con cualquier base de datos – mysql, postgresql, Oracle, mssql, mongodb, etc).

**Comment by Chucho1991** [comment]
como nos repartimos lo que falta?

**Comment by sebas1208** [comment]
Los issues y los labels debemos hacer todos. Lo otros si podríamos repartirnos.

**Comment by sebas1208** [comment]
Amigos ya añadí la lista de suscriptores y las imágenes de las interfaces en la pagina web.

**Comment by VictoriaYanez** [comment]
Falta realizar estos dos puntos:

Guía de como suscribirse al proyecto.
Qué tipo de suscripciones hay y cuáles serían sus roles.
Describir cada uno de los labels, como utilizarlos para los colaboradores.
Dentro de la página web que este implementado la lista de suscriptores con la posibilidad de seleccionar al menos 3 tipos de suscripciones, la de los desarrolladores, la de los colaboradores en general y la de gente interesada.

**Comment by MarlonVP** [comment]
Ya únicamente falta describir los labels y cómo serán utilizados por los colaboradores.

**Comment by VictoriaYanez** [comment]
Todos los parámetros se han completado.
